### ISSUE TITLE
Does MMR regularizer greatly increase the training time? 

### ISSUE THREAD

**Issue by CaoHaoyuan** [max-andr/provable-robustness-max-linear-regions#2]
I trained the LeNetSmall model with mnist dataset on a GTX1080. The expected training time is up to 36 hours for 100 epochs(default value). Is it supposed to be this long? Are there any tricks used in your experiments to accelerate training or I am supposed to simply use multiple GPUs?

**Comment by max-andr** [comment]
Hi,

Yes, training with MMR is indeed slower than standard training. 36 hours on MNIST still sounds like much more than what we have observed (I guess roughly several hours of training on MNIST). But we were using Nvidia P100 GPUs instead, so maybe that's where the difference comes from.

I hope that helps.

Best,
Maksym
